# Usage
#   Start:          docker compose up
#   Stop:           docker compose down

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iframely
    restart: always
    ports:
      - "8061:8061"
    volumes:
      - ./volumes/config.local.js:/iframely/config.local.js
